### ISSUE TITLE
build libtommath before libtomcrypt on win10-64bit + mingw-gcc

### ISSUE THREAD

**Issue by meir100** [libtom/libtommath#121]
in order to build libtomcrypt on win10-64bit + mingw-gcc there is a need
to build libtommath before.

the command:  mingw32-make -f makefile.mingw inside C:\libtomcrypt-develop can not work.
the solution in:  C:\libtommath-develop is:

C:\libtommath-develop> gcc -I. -c *.c
C:\libtommath-develop> ar -r libtommath.a *.o
C:\libtommath-develop> ranlib libtommath.a

and after that: rename C:\libtommath-develop to: C:\libtommath
then the command:  
mingw32-make -f makefile.mingw inside C:\libtomcrypt-develop works.

there is a need to create makefile.mingw in C:\libtommath-develop for this commands:
and maybe a C:\libtommath-develop rename is needed.

C:\libtommath-develop> gcc -I. -c *.c
C:\libtommath-develop> ar -r libtommath.a *.o
C:\libtommath-develop> ranlib libtommath.a

**Comment by karel-m** [comment]
the `makefile.mingw` is now included in libtommath
