### ISSUE TITLE
please add a BSD2 or MIT style  option for the license

### ISSUE THREAD

**Issue by cartazio** [libtom/libtommath#126]
I've been talking with GHC dev collaborators, and we'd like to consider libtommath as a non GPL'd option for ghc's big nat/integer facilities.

to do so, we'd love for you to augment your dual licensing with perhaps a MIT or BSD2 license. 

I realize that wttfyw (wtfpl )/ public domain  dedication *should* be enough, but some people are sticklers, and apparently in some countries the notion of public domain doesn't exist. :(  

i'm happy to help / try  email all the listed contributors if thats something that could be deemed helpful.

Either way this is a fine library and we want to help put it in the hands of more people :)

**Comment by minad** [comment]
@sjaeckel The GHC haskell compiler is considering tommath as an alternative bigint backend. Currently GHC uses GPL-licensed GMP. For static linking an alternative is needed. See https://github.com/ghc-proposals/ghc-proposals/pull/183.

See also https://github.com/libtom/libtommath/issues/76

**Comment by sjaeckel** [comment]
I've contacted @samcv via mail and I'm waiting for an answer. This should (hopefully) be resolved soon.

**Comment by minad** [comment]
@sjaeckel Thank you!

**Comment by minad** [comment]
I have no ideas if lawyers accept the unlicense. The name at least does not sound good, **un**-license.
I am also no lawyer and I find this discussion kind of unnecessary as you mentioned before (Wo kein Kläger, ...). I think the best solution is to just go with something proven like BSD, MIT or Apache. Then the license checking in whatever legal setting should be a non-issue.

**Comment by minad** [comment]
@sjaeckel Any news here?
