### ISSUE TITLE
mtest/mpi.c does not have an open-source license

### ISSUE THREAD

**Issue by dod38fr** [libtom/libtommath#145]
While working on `debian/copyright` file with `cme update dpkg-copyright`, I stumbled on this:

```
$ head mtest/mpi.c
/*
mpi.c

by Michael J. Fromberger <sting@linguist.dartmouth.edu>
Copyright (C) 1998 Michael J. Fromberger, All Rights Reserved

Arbitrary precision integer arithmetic library

$Id$
*/
```

Even if this is a test file, I'm afraid that the mention "All Rights Reserved" means that this file is proprietary.

@creachadair, I believe you're the original author of this file. Would you consider relicensing this file to
the open-source license used by libtommath ? (i.e. [Unlicense](http://unlicense.org/))

All the best

**Comment by creachadair** [comment]
> @creachadair, I believe you're the original author of this file. Would you consider relicensing this file to the open-source license used by libtommath ? (i.e. Unlicense)

That seems fine to me.

**Comment by dod38fr** [comment]
@creachadair Done. Thanks for the quick reply.

All the best

**Comment by sjaeckel** [comment]
> @creachadair Done. Thanks for the quick reply.

true, thanks a lot!
