### ISSUE TITLE
Logic error when it is built

### ISSUE THREAD

**Issue by metinavci** [libtom/libtommath#151]
Hi, 

it gives a warning when the app is built.

**fputc(buf[x]**

Logic error
1st function call argument is an uninitialized value

```
#ifdef BN_MP_FWRITE_C

int mp_fwrite(mp_int *a, int radix, FILE *stream)
{
   char *buf = NULL;
   int err = 0, len = 0, x = 0;
   
   if ((err = mp_radix_size(a, radix, &len)) != MP_OKAY) {
      return err;
   }

   buf = OPT_CAST(char) XMALLOC (len);
   if (buf == NULL) {
      return MP_MEM;
   }
   
   if ((err = mp_toradix(a, buf, radix)) != MP_OKAY) {
      XFREE (buf);
      return err;
   }
   
   for (x = 0; x < len; x++) {
       if (fputc(buf[x], stream) == EOF) {
          XFREE (buf);
          return MP_VAL;
       }
   }
   
   XFREE (buf);
   return MP_OKAY;
}

```
![screen shot 2019-01-31 at 11 19 44 am](https://user-images.githubusercontent.com/1993928/52021726-43fd6b80-254a-11e9-9c7f-ee5148da1dfa.png)

**Comment by czurnieden** [comment]
The buffer `buf` is always filled at the time the function `fgetc(buf[x])` is called but the compiler does not know that, the warning can be safely ignored.

There might be a small change to get rid of that warning if we have some more information: what compiler/IDE + version, what OS + version, and what hardware.

**Comment by metinavci** [comment]
Thank you @czurnieden for the suggestion.

**Comment by czurnieden** [comment]
@metinavci 
> I will update it and see what will happen.

Did anything significant happen or can we close this issue?

**Comment by sjaeckel** [comment]
Please re-open if there's more to add after the update.
