### ISSUE TITLE
Additional maintainers?

### ISSUE THREAD

**Issue by minad** [libtom/libtommath#157]
Hi @sjaeckel,

I am wondering if it would make sense to add more maintainers to the project to speed up development and merging of PRs a bit. For example @czurnieden is quite active.

**Comment by czurnieden** [comment]
> For example @czurnieden is quite active.

I prefer the "worker-bee" status, thank you.

**Comment by minad** [comment]
@czurnieden Ok @sjaeckel Thank you for adding.
