### ISSUE TITLE
Issues according to coverity (tc_xor fixed, fgets not yet fixed)

### ISSUE THREAD

**Issue by minad** [libtom/libtommath#163]
![](https://i.imgur.com/WLB7EnG.png) 

I think this is a false positive but by restructuring the conditions we could avoid it. Still it would make sense to set up travis ci coverity.

**Comment by minad** [comment]
I registered https://scan.coverity.com/projects/libtom-libtommath but it is not yet activated there.

**Comment by czurnieden** [comment]
This is a false positive indeed, the software cannot know that `sign` only holds two values&mdash;that it is a pseudo-bool, so to speak. All static analysers I know have some special kind of comment to handle this situations (vid. e.g.: splint). I doubt they don't have those but Google couldn't find a list for me.

Coverty (their online version) does not allow for a lot of scans per week, only about two dozens or so for our small (~12,000 loc says `cloc(1)`) project. Would that be a problem?

What about other static analysers? There are a lot that are open-source which (not all at once, of course ;-) ) we could pack into a `makefile_test_static_analyser`, or something alike?

And what's about dynamic testing? If I handle memory manually (malloc et al.) I always do a test-run with Valgrind (mostly just `valgrind  --leak-check=full --show-leak-kinds=all`).

And like above: pack into a `makefile_test_dynamic_analyser`, or something alike?

**Comment by minad** [comment]
Yes, the issue was introduced by @fperrad's linting. Before that, I had written it in a more sloppy style, which just checked for truthiness.

**Comment by czurnieden** [comment]
> This is also why it would make sense to go to C99 ;)

Nope, sorry, c90 it is. To much legacy ballast. (doesn't Debian still insist on c90, too?)

> However I had more issues with sanitizers, which could not handle some things.

So does Valgrind. Makes quite a mess with the`long double`. Uses `double` instead but won't tell anybody (e.g.: does not reset the limits in `float.h`), although you can include `valgrind.h` to check if you run inside Valgrind. Took the liberty to add a simple switch in `demo.c`, see `README.md`. It's a bit how-ya-doing but didn't want to add another dependency.

**Comment by minad** [comment]
I don't understand where you've heard that debian requires c90. There are packages in debian which are not c90 and not even c ;) Why should they care?

Valgrind cannot handle long double? I didn't know since I've never used long double. But in general valgrind should have any problems since it emulates the cpu. The only issue I had was with very large mmaps (~ TB), which slow it down. The memory mappings were not used physically, it was just allocated virtual address space. For that case I also added a check if valgrind is running, like you suggested.

What you can do - check for __has_include, check then for __has_include(<valgrind.h>) and then you don't add a depedency this way.

**Comment by czurnieden** [comment]
> I don't understand where you've heard that debian requires c90

It once popped up in one of my diagnostic tests for the Debian build. Can't remember where and how only that it popped up. Hence the parentheses and the question mark.

> check for __has_include

See #160

**Comment by minad** [comment]
The second issue on coverity:

![](https://i.imgur.com/vIrFfAp.png)

**Comment by czurnieden** [comment]
Forgot it the first time, but here it is now: no pictures, please, thank you!

Yes, that is one: must check `fgetc` for EOF.
And initialize `ch` with e.g.: `'0'` to sooth "coverty".

**Comment by minad** [comment]
@czurnieden What is the problem with pics and what do you suggest as quick alternative? I am pragmatic. Even emacs can show pics ;)

**Comment by czurnieden** [comment]
@minad 
> Even emacs can show pics
But not everyone can view them.
Also: pics are not searchable; neither by Google nor by `grep`
So: don't use pics if avoidable (not at **all** costs, of course).

**Comment by minad** [comment]
I agree in general :)

**Comment by czurnieden** [comment]
And before someone asks: "But whattabout the out-of-bounds error?!?!", there is none. The cast to `unsigned` folds over in case the result of `ch - (int)'('` is negative and the result of the folding makes `(mp_s_rmap_reverse_sz < pos)` always true if `sizeof(int)` is large enough.

The check of `fgets` is not *that* necessary but it would get `mp_fread` a more deterministic behaviour.

Also: the I/O functions do not get tested very thoroughly in demo.c now. Should they?

**Comment by minad** [comment]
@czurnieden Hmm, maybe it would make sense to create a new well structured test suite (additional to what is there now). Like one test_mp_* function per mp_* function or something like this. Then it would also be more obvious what is being tested and what is not.

**Comment by czurnieden** [comment]
That would be a lot of work!
And you are willing to do it?
Respect!

**Comment by minad** [comment]
@czurnieden @sjaeckel There you go https://github.com/libtom/libtommath/pull/167

**Comment by sjaeckel** [comment]
@minad can you please add me to the coverity project

**Comment by minad** [comment]
@sjaeckel Sure!

**Comment by sjaeckel** [comment]
closed via #166

**Comment by minad** [comment]
There is still the fgets issue

**Comment by sjaeckel** [comment]
Didn't you come to the conclusion that this is a false positive?

IMO #166 was already borderline, but this one should not be fixed on our side... 

coverity says "The value of pos is now -41." but `pos` is an `unsigned` ... I think that should be enough to make them fix their code...

**Comment by minad** [comment]
I didn't come to a conclusion yet.

**Comment by minad** [comment]
@sjaeckel Let's add a check for fgetc == EOF as czurnieden suggested.

**Comment by sjaeckel** [comment]
> Let's add a check for fgetc == EOF as czurnieden suggested.

sure, make it a `while (ch != EOF)` or something like that ...

**Comment by minad** [comment]
fixed by #277
