### ISSUE TITLE
Helper.pl parses comments, too

### ISSUE THREAD

**Issue by czurnieden** [libtom/libtommath#207]
If you comment about the intricacies of  `sizeof` in a comment, helper.pl reacts with
`[sizeof_no_brackets]`
See for example line 55 in `bn_mp_n_root_ex.c` in #189 (changed now, was a single `sizeof` before)
Can you change it @karel-m without much work or shall we just put a line or two in the documentation?

**Comment by minad** [comment]
fixed by #234
