### ISSUE TITLE
Pick a few compiler versions and test against them

### ISSUE THREAD

**Issue by minad** [libtom/libtommath#208]
Pick a few "supported" compiler versions and test against them on Travis. Right now we are just testing against what is there, whatever that is.

This does not mean that older or other compilers won't work, since tommath is very conservative in that regard. They are just not tested during CI runs.

**Comment by minad** [comment]
We could even test old GCCs like 4.* with relaxed warning settings.

**Comment by czurnieden** [comment]
Why don't you give it a start and open a Wiki page and make a list with the ones you had successfully build LTM (dont' forget to add the LTM version, please) with?
Once we have a bunch we can update the docs (`bn.tex`).

**Comment by minad** [comment]
This issue is mainly about getting the CI configured that we get those compilers tested, not so much about documenting successful builds. But documentation is important and you already started such a thing for different platforms, right?

**Comment by czurnieden** [comment]
> [...]you already started such a thing for different platforms, right?

Feel free to add to it.

**Comment by sjaeckel** [comment]
> Feel free to add to it.

probably if it's going to be bigger it deserves its own wiki page?!

**Comment by minad** [comment]
closed via #225
