### ISSUE TITLE
Request: Two's complement math functions

### ISSUE THREAD

**Issue by hikari-no-yume** [libtom/libtommath#32]
These are useful since modern CPUs use two's complement integers, so they could be used as drop-in arbitrary-precision replacements for native integer operations. Python's bitwise operators behave like this on bignums.

In particular, the useful functions:
- Ones' complement - trivial to implement, this is just `(-n - 1)`, has the same result as bitwise NOT on two's complement system
- Arithmetic right shift with sign extension - also trivial to implement: if op1 is negative, get its one's complement, do your usual logical right shift of that (LibTomMath's right shifts are logical right shifts), then get the one's complement of the result of that shift.
- Two's complement OR, XOR, AND - trickier to implement. If both inputs are positive, do your usual \<bitwise op\>. If one or both inputs is negative, you must convert the negative ones to their two's complement representation (if both are negative, they must be two's complement representations **for the same power of two/width in bits**). Then, you must do \<bitwise op\> on the two values. Then, do a \<bitwise op\> on the fake sign bits (1 is negative, 0 is non-negative), and if it results in 1, get the two's complement of the result of the earlier bitwise op. 

If you want an idea of implementation:
- Here's how Python does bitwise ops: https://hg.python.org/cpython/file/628acf7dbc8d/Objects/longobject.c#l4171
- Here's how I did it using LibTomMath functions in my fork of the PHP codebase, following how Python did it: https://github.com/TazeTSchnitzel/php-src/blob/481bc1ea3986ab596b3a1860b1693cfa2769c845/Zend/zend_bigint_libtommath.c#L768 (probably easier to understand)

For test cases:
- https://github.com/TazeTSchnitzel/php-src/tree/bigint/tests/lang/operators

This is the successor issue to the previous one about just right shifts: https://github.com/libtom/libtommath/issues/30

Also, before this is implemented, and even if this isn't implemented, we should probably note explicitly that we _don't_ do two's complement operations for right shifts, AND, OR and XOR, to avoid user confusion.

:)

**Comment by minad** [comment]
@sjaeckel This one too.

**Comment by sjaeckel** [comment]
closed via #124
