### ISSUE TITLE
Deprecation of 8-bit support (MP_8BIT) in LibTomMath

### ISSUE THREAD

**Issue by czurnieden** [libtom/libtommath#353]
All code for 8-bit architectures (`MP_8BIT`) is deprecated and will be removed in version <del>1.2.0</del> 2.0.0 without further notification.

So if you need support for 8-bit place your arguments here and we might keep it.
But supporting 8-bit is a **large** pain in the behind so your arguments must be **really** good!

It would also be nice to drop a note in this thread if you plan to fork LTM to keep MP_8BIT supported elsewhere.

<a href="https://www.goodreads.com/quotes/40705-but-the-plans-were-on-display-on-display-i-eventually"><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/I_See_You.jpg/800px-I_See_You.jpg"></a>

**Comment by minad** [comment]
fixed by PR #349

**Comment by czurnieden** [comment]
> fixed by PR #349

Uhm, no, not fixed by anything but time and that time has not come yet . This "issue" is meant as an anouncement because, as you already found out yourself, there is no dedicated mechanism here for anouncements.

But you could have fixed that anouncement when you added it to the 2.0.0 milestone and change the version number from 1.2.0 to 2.0.0 here and in the wiki page.

Added picture of leopard for clarity.
