### ISSUE TITLE
Misplaced closing parenthesis in mp_div()

### ISSUE THREAD

**Issue by jmalinen** [libtom/libtommath#36]
This contribution to a version of LibTomMath included in hostap.git seems to be applicable to the current version of LibTomMath bn_mp_div.c as well:
http://w1.fi/cgit/hostap/commit/?id=74d912f134984fac1a5d95ed001af1564a1191fc

(i.e., the mp_init_multi() call in mp_div() has a misplaced closing parenthesis which can result in the MP_MEM error code getting returned incorrectly as 1)

**Comment by tomstdenis** [comment]
Agreed the commit looks good to pull in.

**Comment by tomstdenis** [comment]
Applied fix.
