### ISSUE TITLE
helper.pl - check that ifdef guard is consistent with function being defined

### ISSUE THREAD

**Issue by minad** [libtom/libtommath#374]
see #373

**Comment by sjaeckel** [comment]
Was this even at the point of opening a valid issue?

It seems like [helper.pl:333](https://github.com/libtom/libtommath/blob/develop/helper.pl#L333) handles this already correctly and #373 was related to `bn_deprecated.c` which doesn't exist anymore.

**Comment by minad** [comment]
I think I once had an issue with bn_deprecated. At that point it was a valid issue
