### ISSUE TITLE
Discuss removal of doc/tommath.src

### ISSUE THREAD

**Issue by sjaeckel** [libtom/libtommath#383]
That's the book of Tom and still part of the documentation, but it isn't maintained anymore and should be removed. Its latest updated by Tom was in v0.39 and nobody took care of it since then.

**Comment by minad** [comment]
I thought you already removed it? I don't see a problem in removing it. The historical version can still be obtained from the git history. Alternatively you could add a git repository libtom/libtommath-book to the organisation?
