### ISSUE TITLE
MP_HAS and missing implementation

### ISSUE THREAD

**Issue by minad** [libtom/libtommath#389]
There are some functions like mp_sqr which may call a fast variant if possible. In the default case however s_mp_sqr is called. However we also have the s_mp_sqr call guarded by MP_HAS. I think we should always provide a default implementation such that the functions never fail.

This applies to multiple other functions too.

**Comment by minad** [comment]
Ping @sjaeckel @czurnieden

**Comment by minad** [comment]
Right now I am fiddling with log_u32 a bit and I am not so sure anymore. Sometimes you really want to configure a function down such that it works only on a subset of inputs.

**Comment by czurnieden** [comment]
> I think we should always provide a default implementation such that the functions never fail.

If somebody included the function it should work, no matter how, yes.

> Right now I am fiddling with log_u32 a bit and I am not so sure anymore.

What is your exact problem there?
The only faster version is the one using native types if `a->used == 1`. The bigint version should work as well in that case, just a tad bit slower, especially for `MP_DIGIT_BIT == 60`. They native version cam go into its own (private) version to avoid compiling it in if memory is sparse (e.g.: could be excluded in the `LOW_MEM` branch). (Yes, I could have done it already, but I have only two hands ;-) )
Or do I misunderstand you?

**Comment by minad** [comment]
In principle I agree with the statement that the functions should always work. However for example in the log case I can configure the function now such that it only works for power of two bases if I only need that.

**Comment by minad** [comment]
@czurnieden ok to close I guess?

**Comment by czurnieden** [comment]
>  However for example in the log case I can configure the function now such that it only works for power of two bases if I only need that.

Ah, now I understand what you meant (I hope ;-) ), thanks!

> @czurnieden ok to close I guess?

In that case: yes.
What you already did.
I'm too slow ;-)
