### ISSUE TITLE
Deprecated function still listed in the user manual

### ISSUE THREAD

**Issue by justinethier** [libtom/libtommath#406]
The user manual for 1.2.0 / master lists `mp_expt_d` even though that function is now deprecated in favor of `mp_expt_u32`.

**Comment by minad** [comment]
Thanks for reporting! We will revise the manual soon since it got out of sync with the development version. See #395.

You seem to use ltm, in cyclone, your scheme implementation. It would be interesting where the library is used right now.

* Cyclone
* Tcl
* Moarvm
* Tomcrypt
* ...

**Comment by sjaeckel** [comment]
I've added https://github.com/libtom/libtommath/wiki/Projects-using-libtommath

**Comment by minad** [comment]
subissue of #395
