### ISSUE TITLE
MP_DIGIT_BIT==8*sizeof (mp_digit)

### ISSUE THREAD

**Issue by minad** [libtom/libtommath#420]
Why are we not always having `MP_DIGIT_BIT==8*sizeof (mp_digit)-1`? I ran tests with MP_DIGIT_BIT 63 and it worked. I think @czurnieden explained me once why this is not the case, but I forgot.

**Comment by sjaeckel** [comment]
I only found https://github.com/libtom/libtommath/issues/48#issuecomment-175081513

**Comment by minad** [comment]
Ok, I have to understand this better. The thing is that we also have 31 bit which is weird then. Furthermore we could add some static assertions at some places which would break if digit_bit is too large? This would help a lot I guess.

**Comment by minad** [comment]
I think we could try to use the full digits (MP_DIGIT_BIT=8*sizeof(mp_digit)). First, addition with carry of digits must be handled differently (either by adding mp_words or by optionally using some compiler builtin). Second, the comba multiplier gets more difficult since we cannot use an mp_word as accumulator, but have to use an three mp_digits (mp_digit _W[3], instead of mp_word _W). See also #429.
