### ISSUE TITLE
remove logs/

### ISSUE THREAD

**Issue by minad** [libtom/libtommath#423]
@sjaeckel Is it necessary to have those in the source distribution? We should probably rather generate the logs for each release and put them on the website?

**Comment by sjaeckel** [comment]
hmm probably it'd be best to do something with them... like have (a) reference machine(s) and make nice graphs showing the performance difference of versions?

**Comment by sjaeckel** [comment]
but yes, they're not needed in the sources

**Comment by minad** [comment]
Ok, let's remove them then!

**Comment by sjaeckel** [comment]
I'll add this to #425 okay?

**Comment by minad** [comment]
Yes please! You can also improve #425 as we discussed there. I can take a look later, afk now
