### ISSUE TITLE
Main Website still mentions wtfpl

### ISSUE THREAD

**Issue by minad** [libtom/libtommath#427]
@sjaeckel https://www.libtom.net/

**Comment by sjaeckel** [comment]
better now?

**Comment by minad** [comment]
Good. I guess some projects are still wtfpl - for example poly doesn't seem to have seen upgrades recently.

**Comment by sjaeckel** [comment]
> I guess some projects are still wtfpl

all besides ltm are still WTFPL

> doesn't seem to have seen upgrades recently

that's a nice expression for "no upgrades for 15 years"

**Comment by minad** [comment]
Hehe :) I thought ltc is also unlicense?

**Comment by sjaeckel** [comment]
not yet

**Comment by sjaeckel** [comment]
or as @sebastianas put it https://github.com/libtom/tomsfastmath/pull/23#pullrequestreview-294016567 "Is this really a relicense?"
