### ISSUE TITLE
Failed to compile using Debug mode in my own project

### ISSUE THREAD

**Issue by Jeremy203** [libtom/libtommath#485]
Hello!
I am having trouble using libtomcrypt.

libtomcrypt and libtommath's lib files compile normally.
But when I use Debug mode to compile in my projects and link them, I get the following error message.

> 1>tommath.lib(bn_s_mp_rand_platform.obj) : error LNK2019: unresolved external symbol s_read_arc4random referenced in function s_mp_rand_platform
> 1>tommath.lib(bn_s_mp_rand_platform.obj) : error LNK2019: unresolved external symbol s_read_getrandom referenced in function s_mp_rand_platform
> 1>tommath.lib(bn_s_mp_rand_platform.obj) : error LNK2019: unresolved external symbol s_read_urandom referenced in function s_mp_rand_platform
> 1>tommath.lib(bn_s_mp_rand_platform.obj) : error LNK2019: unresolved external symbol s_read_ltm_rng referenced in function s_mp_rand_platform

Everything works fine with Release compilation.
Am I missing something?
Thank you!

(Using VS 2017 and Windows x64)

**Comment by sjaeckel** [comment]
Please have a look at the sources of mp_rand_platform there should be a comment explaining your issue. 

Sorry for brevity, I'm on mobile.

**Comment by Jeremy203** [comment]
Thank you! The issue was resolved.
