### ISSUE TITLE
Redefinition of macro MIN / MAX

### ISSUE THREAD

**Issue by karel-m** [libtom/libtommath#49]
HP ANSI C compiler (HP-UX PARISC)
```
cpp: "src/ltm/tommath_private.h", line 21: warning 2001: Redefinition of macro MIN.
cpp: "src/ltm/tommath_private.h", line 23: warning 2001: Redefinition of macro MAX.
```

Not a big deal, I am posting this just in case we want to keep "no compiler warnings during build" strategy

**Comment by TazeTSchnitzel** [comment]
Does this only happen on that compiler? Is it redefining some macro that compiler provides, or redefining one of its own?

**Comment by karel-m** [comment]
It seems that `#include <limits.h>` causes this warnings

This is small demo:
```
#include <limits.h>

#define MIN(x,y) (((x) < (y)) ? (x) : (y))
#define MAX(x,y) (((x) > (y)) ? (x) : (y))

int main(void) {
  return MAX(1,6) + MIN(7,9);
}
```
compiler warning:
```
$ cc -c test.c
cpp: "test.c", line 3: warning 2001: Redefinition of macro MIN.
cpp: "test.c", line 4: warning 2001: Redefinition of macro MAX.
```

**Comment by TazeTSchnitzel** [comment]
This seems like a quirk of the compiler, since this isn't in the C standard.

Would it cause a problem, though? If you look in `limits.h` itself, does it define MIN and MAX differently to us?

**Comment by czurnieden** [comment]
@TazeTSchnitzel No, it's a programmer's quirk and I'm sometimes guilty of it, too ;-)

If you use the C-preprocessor to define something you should check if the variable has been taken already. For example by

``` C
#ifdef FOOBAR
#undef FOOBAR
#define FOOBAR "barfoo"
#endif
```

Or, as seen more often (to make changes at compile time easier) by:

``` C
#ifndef FOOBAR_LIMIT
#define FOOBAR_LIMIT 123
#endif
```

Redefinition is allowed but not always intended by the programmer, so the compiler plays nice and utters a warning. Code, especially large code-bases with many files should avoid to trigger any compiler warnings (and no, switching warnings off is not a proper solution! ;-) so you can see the more serious warnings about the stuff you just implemented .

i don't know which system @karel-m is on but I could find a definition of `MAX` in `/usr/include/x86_64-linux-gnu/sys/param.h` but it is not bound to `limits.h` and hence I cannot repeat the behaviour by including `limits.h` only by including `sys/param.h`.

I would implement the first version above and just `#undef` anything before defining it.

**Comment by TazeTSchnitzel** [comment]
> No, it's a programmer's quirk and I'm sometimes guilty of it, too ;-)

> If you use the C-preprocessor to define something you should check if the variable has been taken already.

I understand that. I'm saying that `MAX` being defined by `limits.h` sounds like a quirk of the HP compiler.

**Comment by karel-m** [comment]
at HP-UX box in question `MAX` and `MIN` are defined in `/usr/include/sys/param.h` like this:
```
#define MIN(a,b) (((a)<(b))?(a):(b))
#define MAX(a,b) (((a)>(b))?(a):(b))
```
And in `/usr/include/limits.h` there is 
```
#ifdef _INCLUDE_HPUX_SOURCE
#  include <sys/param.h>
...
#endif /* _INCLUDE_HPUX_SOURCE */
```
And,no, I have no idea why is `_INCLUDE_HPUX_SOURCE` defined.

What about to "protect" defines in libtommath_private.h like this?
```
#ifndef MAX
#define MAX(x,y) (((x) > (y)) ? (x) : (y))
#endif
```

**Comment by czurnieden** [comment]
@karel-m Only if you know for sure that the already defined `MAX` is the correct one, otherwise undefine the old one and define the one you need. Otherwise it is a good candidate for the so called Heisenbug ;-)

**Comment by sjaeckel** [comment]
I'd also prefer to undef it. Doesn't even have to be conditional IIRC!? Just always undef before the define.

**Comment by tomstdenis** [comment]
It should be save to just use #ifndef and what not... How fucked up could a vendors MAX/MIN macros be?
