### ISSUE TITLE
mtest cannot be fed to test anymore?

### ISSUE THREAD

**Issue by tomstdenis** [libtom/libtommath#50]
I've been out of the loop for a while but the output of mtest should be passable to test without error.  What's changed?

**Comment by tomstdenis** [comment]
I went back to 0.40 and 0.39 tags and it fails there too.  I wonder if mpi (mtest's lib) is failing to build properly under a modern compiler/etc?

**Comment by tomstdenis** [comment]
A quick check with TFM shows that LTM is correct (in this particular exptmod vector) and MPI is wrong.  So what's changed in mpi?

**Comment by sjaeckel** [comment]
Uhm I didn't try it out for some weeks but it isn't that long ago that I saw it working.

**Comment by tomstdenis** [comment]
I'm on a 64-bit amd64 box doing "make test mtest" and then "mtest/mtest | ./test" and it dies on the first test 100% of the time.  I took the #s out and threw them in tfm and ltm is the same (presumably right).

**Comment by tomstdenis** [comment]
I'll try to write some num theory tests against mpi and see what happens.

**Comment by sjaeckel** [comment]
I just see that it's also failing on this machine, my regular testing is done on an older core2duo, here it's an i5...

**Comment by tomstdenis** [comment]
I did a trivial 17^65519 % 65521 and then multiplied it by 17 and got 1.  So fundamentally it's "working" a little.  I don't know where it's breaking down.  I could try a larger modulus ...

**Comment by sjaeckel** [comment]
ah good 'ol gcc optimization

if I compile with e.g. `COMPILE_DEBUG=1` it runs fine

btw there's also already a bug open for tfm on ARM...

**Comment by sjaeckel** [comment]
works with `-O1` doesn't with `-O2`

**Comment by tomstdenis** [comment]
Yes it runs with COMPILE_DEBUG=1 for me as well...

**Comment by tomstdenis** [comment]
Specifically I can compile ltm normally and compile mtest with DEBUG and it works.

As for tfm/arm we can look at that later.  I'd like to get 0.43 organized.

**Comment by sjaeckel** [comment]
I propose this as patch

```
diff --git a/makefile b/makefile
index dbf085b..7936aa7 100644
--- a/makefile
+++ b/makefile
@@ -94,7 +94,7 @@ test_standalone: $(LIBNAME) demo/demo.o
 
 .PHONY: mtest
 mtest:
-       cd mtest ; $(CC) $(CFLAGS) mtest.c $(LFLAGS) -o mtest
+       cd mtest ; $(CC) $(CFLAGS) -O1 mtest.c $(LFLAGS) -o mtest
 
 timing: $(LIBNAME)
        $(CC) $(CFLAGS) -DTIMER demo/timing.c $(LIBNAME) $(LFLAGS) -o ltmtest
```

makes it work for me

**Comment by tomstdenis** [comment]
It'd be nice to know why mpi is dying.  I suspect it's a bug that's always been present but newer compilers expose it based on spills/access patterns.

For now I'd go as far as to say -O0 and just disable all optimizations.

Eventually what I'd like to do is replace mpi.c with a version of ltm.  The point of mtest vs test is to have a bignum lib that doesn't move compared to new code.  If we "bless" a version of ltm we can just use that in its place.

**Comment by tomstdenis** [comment]
I pushed a commit that disables optimization and mtest vs test works again.

**Comment by sjaeckel** [comment]
Would be okay for me to replace mpi.c.

**Comment by tomstdenis** [comment]
Let's aim for that to be a 0.44 goal to swap in 0.43 as mpi.c

**Comment by TazeTSchnitzel** [comment]
Sounds good. Did 0.43 have any particular known issues?

**Comment by tomstdenis** [comment]
mpi.c produces bad outputs with gcc 5.3.x and O2 or higher.  I suspect it's a bug that is being presented because of changes to the code generation in gcc.

Eventually we'll just move to replace mpi with a static version of ltm.
