### ISSUE TITLE
s_read_wincsp leaks handle

### ISSUE THREAD

**Issue by mabuchner** [libtom/libtommath#519]
The `s_read_wincsp` function calls [`CryptAcquireContextW`](https://docs.microsoft.com/en-us/windows/win32/api/wincrypt/nf-wincrypt-cryptacquirecontextw)

https://github.com/libtom/libtommath/blob/2cec6addaf4acbd8250611ec4cecadf1f4d655ee/s_mp_rand_platform.c#L38

but the corresponding [`CryptReleaseContext`](https://docs.microsoft.com/en-us/windows/win32/api/wincrypt/nf-wincrypt-cryptreleasecontext) function is never called.

Hence, the handle is never released and leaks.

**Comment by mabuchner** [comment]
tommatch v1.1.0 was still calling ` CryptReleaseContext` at application exit

https://github.com/libtom/libtommath/blob/v1.1.0/bn_mp_rand.c#L57

**Comment by sjaeckel** [comment]
16ff016ebeca751d8edcfb7e1422c6eb7b6bc113 shows the reasoning behind this change.
