### ISSUE TITLE
Is the memory representation stable?

### ISSUE THREAD

**Issue by nomeata** [libtom/libtommath#520]
Maybe this is documented somewhere, but I couldn't find it:

Will new versions of libtommath always be compatible with old versions in the memory representation, or should I not assume that to be the case?

**Comment by sjaeckel** [comment]
What exactly do you mean?

Somehow storing the memory of `mp_int.dp` and the other properties and then re-constructing the `mp_int` from that?

How `mp_int.dp` is represented depends on your configuration of ltm ... `MP_{16,31,32,64}BIT` which decides on the value of `MP_DIGIT_BIT` ...

If you make sure that you use the same configuration then `mp_int.dp` should be stable.

@czurnieden please correct me if I'm wrong.

**Comment by nomeata** [comment]
Yes, imagine a programming language that can dump it's heap to file and read it later, possibly with a newer version of libtommath.

**Comment by sjaeckel** [comment]
Should be feasible but keep in mind that your compiler has some words in this game as well. Especially how the `mp_int` is structured in memory is the compiler's choice.

**Comment by nomeata** [comment]
Good point, thanks. But it's already good to know that you don't reserve the right to change the meaning of the data.

**Comment by sjaeckel** [comment]
I'd still like to hear the opinion of @czurnieden on this :)

**Comment by czurnieden** [comment]
> I'd still like to hear the opinion of @czurnieden on this :)

Nothing to add here, you said it all :-)

Maybe endiannes could be an additional problem, but that is easily controlled for.

> Yes, imagine a programming language that can dump it's heap to file and read it later, possibly with a newer version of libtommath.

So you can do something like the following?

```console
$ compute_a_lot_of_things &
$ killall -e compute_a_lot_of_things -s USR1
  compute_a_lot_of_things: save current state? [y/n] y
  Current state saved in file: "tmp.dFP8UifIL0"
  Exiting.
...
$ compute_a_lot_of_things -f tmp.dFP8UifIL0 &
  Going on using state saved in file: "tmp.dFP8UifIL0"
$
```

That could even fail if everything is the same (LTM, compiler, OS, arch, etc.) if you do it by dumping the heap only; there are just too many variables in the whole game to make it feasible.

Although using heap-dumps of individual `mp_int`s should work under certain conditions, there is a much more portable way to do it:

LTM offers methods to print and read the binary representation of individual `mp_int`s (`mp_*pack` and `mp_*_*bin`) and with a bit of extra structure to connect those `mp_int`s to the correct points in your AST you could implement such a "partial hibernation" (named so for lack of a better expression) for your language.
