### ISSUE TITLE
mp_is_square says 0 is not a square

### ISSUE THREAD

**Issue by guidovranken** [libtom/libtommath#521]
mp_is_square says 0 is not a square, but it is.

**Comment by czurnieden** [comment]
This is the original behaviour  (Try `git log --follow -p --  mp_is_square.c`) and other software, especially LibTomCrypt needs to be checked before we change something here.

But at least the documentation should get an update; the function `mp_is_square` is listed without a proper description.

Thanks a lot!

**Comment by sjaeckel** [comment]
Thanks for reporting!

Closed via #522

**Comment by guidovranken** [comment]
Thank you for fixing.
