### ISSUE TITLE
Request: change argument `fast` in `mp_n_root_ex` to remainder

### ISSUE THREAD

**Issue by czurnieden** [libtom/libtommath#66]
Does the argument `fast` in `mp_n_root_ex` has some plan behind it or can it be replaced by `mp_int *d` for the remainder?

Putting the remainder in  `mp_n_root` would be better, but that would change the API, so ...

**Comment by sjaeckel** [comment]
well the `fast` parameter is passed forward and decides in `mp_expt_d_ex()` whether it will use the fast or constant-time implementation. I added this for heimdal , but unfortunately it hasn't been merged there yet (c.f. https://github.com/heimdal/heimdal/issues/273 and some other issues in this and their repositories)...

**Comment by sjaeckel** [comment]
do you still need that? if no, this can be closed... if yes...

> Does the argument `fast` in `mp_n_root_ex` has some plan behind it or can it be replaced by `mp_int *d` for the remainder?

how about adding `mp_n_root_with_rem(const mp_int *a, mp_digit b, mp_int *c, mp_int *d, int fast)` or `mp_n_root_full()`?

> Putting the remainder in `mp_n_root` would be better, but that would change the API, so ...

...we also shouldn't change the meaning of an argument...

**Comment by czurnieden** [comment]
`mp_n_root_ex` is not connected to `mp_expt_d_ex`, or is it?
I think the extra function `mp_n_root_with_rem` is a good idea. It's just a call, an exponentiation and a subtraction. But not for this version, I s'ppose? ;-)
No, this request can be closed, of course.
