### ISSUE TITLE
mp_invmod(a,b,c) fails for a=1, b=1

### ISSUE THREAD

**Issue by karel-m** [libtom/libtommath#67]
And it seems to be due to the fact that optimised `fast_mp_invmod` is not able to handle this case.

A possible fix for `bn_mp_invmod.c` might look like this:

``` diff
-  if (mp_isodd (b) == MP_YES) {
+  if ((mp_isodd (b) == MP_YES) && (mp_cmp_d (b, 1) != MP_EQ)) {
     return fast_mp_invmod (a, b, c);
   }
```

Originally reported by @pjacklam as a bug in `Math::BigInt::LTM` (perl bindings for libtommath).

**Comment by timo** [comment]
we also stumbled over this in MoarVM, our perl6 VM, where expmod(42, -1, 1) would hang infinitely. applying this change makes it terminate, though.

Could this be merged, then?

**Comment by zoffixznet** [comment]
[indirectly using this via MoarVM](https://rt.perl.org/Ticket/Display.html?id=130713#txn-1497738) and found that while `expmod(42, -1, 1)` no longer hangs, `expmod(42, -1, 7)` still does.

**Comment by sjaeckel** [comment]
Well for me also `expmod(42, -1, 1)` still hangs...

**Comment by sjaeckel** [comment]
can you try this out please

**Comment by timo** [comment]
looks good to me. moarvm now has a "fix_for_expmod" branch that points at a libtommath repo fork that has the fix/67 branch merged. it doesn't hang any more for the cases shown in the commit and also for a whole bunch of other combinations of values
