### ISSUE TITLE
Please confirm the result of mp_exptmod

### ISSUE THREAD

**Issue by dmitry-lipetsk** [libtom/libtommath#73]
Hello.

Could anybody confirm the following result of mp_exptmod(G,X,P):

[decimal numbers]
G: 134579305646567588532446688779867257713771275107057684621479634689650080773159393062143615968462797569598762456137907426092218976711352664901100324510362588000972245190812583367951716257843798290510401392628339635570171029437522098146169720032322549061259568330770328939946360070887343808349359575738583288513

X: 59621918710175437070932497031782508368941263753349421666170603004927957539961933633126185597358384597639320471341244211399512691371990377023221395581281196351551942288799914425527074844447065151470655714679461853044096538898382911610773551224067179736028363490008331414981702505494439632826269013715639300607

P: 161854874649776085868045952190159031555772097014435707776279513538616175047026058065927714606879676219064271341818754038806823814541886861147177045257236811627035155212310813305487929926508522581710604504792711726648563877865328333166885998671854094528177699206377434633696300213499023964016345755132798642663

Result:
101301173055927651077022731855711438828812096932633287901900987654023094677508334006010080425994011956816952131806632586952937438745717497636453981418484521946523641731799712935430148584311675467744159957145015439883211966248185614742819253200041306084133542299253931058698197750953799169870496336490295415615

-----
If result is correct - how I can to check this result through other libtommath functions?

Thanks.

**Comment by karel-m** [comment]
Correct `Result` is IMO 137483489176385968890069744401904874416760569619806877423289046921638353530491290775137940539150267906609434615608258395577809903128532069444584109878287009732300021272277359300386996025541517629363320438878286135496326187222121347670538363804973135008636384132940971509824375539379006956869167854145224396240

**Comment by dmitry-lipetsk** [comment]
Thanks for answer.

I think, you are right.

This combination of G/X/P calculated through mp_exptmod_fast.

And s_mp_exptmod (orignal version) returns the same result.

I've got the "10130117305592...." from my (modified) s_mp_exptmod :(

Please do not close this issue - I want compare my s_mp_exptmod and original s_mp_exptmod.

Thanks, again.

**Comment by dmitry-lipetsk** [comment]
I found and corrent mistake in my code.
