### ISSUE TITLE
Error compilation with makefile.msvc under VS 2017

### ISSUE THREAD

**Issue by koh-osug** [libtom/libtommath#74]
When using the commandile `nmake -f makefile.msvc` to compile the library I get:

    CFLAGS = /I. /Ox /DWIN32 /W3  /Fo$@

    macro '$@' is illegal in the context of batch rule 'rule'

The quick fix is to remove  `/Fo$@`.

**Comment by karel-m** [comment]
Are you trying `develop` branch? if not, please do.

**Comment by koh-osug** [comment]
The libtomcrypt build works. I was using the downloadable zip from the develop branch.
