### ISSUE TITLE
tommath_class.h includes itself

### ISSUE THREAD

**Issue by jomsdev** [libtom/libtommath#81]
I got a bit lost among all the `#ifdef`,  `#else` and `#endif` but, if I am not wrong, tommaath_class.h includes itself [here](https://github.com/libtom/libtommath/blob/develop/tommath_class.h#L1050).

Is it a human error or it is done on purpose?

**Comment by tomstdenis** [comment]
Yes, it's meant to be a multiple pass to include functions.  In theory you
can build LTM by only enabling certain classes of functions and then this
includes itself 3 times to sort out which dependencies are needed.

It's kinda archaic and I wouldn't recommend it for all but the most memory
constrained devices...

**Comment by jomsdev** [comment]
I was not aware of that technique, thank you for the information.

Problem solved.
