### ISSUE TITLE
Not supported __int128 MSVC 2015 x64

### ISSUE THREAD

**Issue by atvise** [libtom/libtommath#87]
Hi,

i want to compile libtommath with my MSVC 2015 x64 compiler and this error message comes up:

"libtommath\tommath.h(67): error C4235: nonstandard extension used: '__int128' keyword not supported on this architecture"

Do you know any workaround/fix for that problem? Thank you very much!

Regards,
atvise

**Comment by czurnieden** [comment]
They said to implementit but never did and do not even plan it according to this post here (last entry (the closing notice) from July 2016) 

https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/2643778-support-int128-on-64-bit-platform

Or

https://github.com/FStarLang/kremlin/issues/2

which has a bit more discussion.

For now you are restricted to the 32-bit implementation of libtommath if you want to use MSVC or use a different C-compiler (e.g. mingw, the GCC port for Windows).

**Comment by sjaeckel** [comment]
Please re-open if you have further questions/comments.
