### ISSUE TITLE
index section in latest release pdf broken

### ISSUE THREAD

**Issue by rofl0r** [libtom/libtommath#98]
the whole index section is less than a page and features only a handful of functions.

**Comment by sjaeckel** [comment]
if you're talking about `tommath.pdf` this index has always been like that... `bn.pdf` has a more complete index...

**Comment by rofl0r** [comment]
oh, i assumed the index would be generated programmatically somehow.
that said, even if it was like that in the past, that doesn't really change the fact that it's utterly incomplete (i.e. broken) ;-)

**Comment by sjaeckel** [comment]
better? ;-)

**Comment by rofl0r** [comment]
i can't tell, since i dont have latex (it's not been added to my distro yet). woud you mind uploading the result ?

**Comment by sjaeckel** [comment]
[tommath-v1.0.1-69-g2bf7d3a.pdf](https://github.com/libtom/libtommath/files/1570126/tommath-v1.0.1-69-g2bf7d3a.pdf)

**Comment by rofl0r** [comment]
wow, that's a huge improvement, thanks!
